### PR TITLE
Fix node-gyp builds on Windows

### PR DESCRIPTION
**Pull request by indutny**
The `msvs` GYP generator's support for uppercase extensions in actions is broken for Windows. It creates lookup table with uppercase extensions, but converts extensions to lowercase before looking them up in the table. The MASM errors happen because `msvs` generator also has a default handler for `.s` extension. The solution is to use symbolic links to rename `.S` files to all lowercase `.preasm` files.

Fix: #133

### CODE REVIEW

**Comment by indutny** [comment]
Oh snap, something isn't right. It still doesn't build on my Parallels VM. Give me a bit more time to figure it out.

**Comment by indutny** [comment]
That was just bad symlinks support on Windows' git. Fixed now.

**Review by addaleax — APPROVED** [review]
@indutny Thanks for the pings :)

**Comment by addaleax** [comment]
`📦  ffi-napi@4.0.2` :)

**Comment by indutny** [comment]
Yay! Thank you!

**Pull request merged**
