### PR TITLE
deps: update libffi to v3.3+1a4b78

### PR DESCRIPTION
**Pull request by indutny**
Update libffi to the latest release (v.3.3) and an [extra commit][] to support
building on the M1 macs. At this point the patch supports following platforms:

- [x] `freebsd/ia32` (probably works)
- [x] `freebsd/x64`
- [ ] `linux/arm`
- [x] `linux/arm64`
- [x] `linux/ia32`
- [x] `linux/x64` 
- [x] `mac/arm64`
- [x] `mac/ia32` (probably works)
- [x] `mac/x64`
- [ ] `openbsd/x64`
- [ ] `solaris/ia32`
- [ ] `solaris/x64`
- [x] `win/ia32`
- [x] `win/x64`
- [x] `win/arm64`

---

The process for adding support for unchecked platforms above is following:
```sh
git clone git://github.com/indutny/node-ffi-napi -b feature/macos-arm64
cd node-ffi-napi/deps/libffi
./configure --enable-static --disable-shared --disable-builddir --with-pic
cp -lf {fficonfig.h,include/ffi.h,include/ffitarget.h} config/<platform>/<cpu-arch> 
rm {fficonfig.h,include/ffi.h,include/ffitarget.h}
cd ../..
npm install
npm test
```

If the tests pass - the `config/<platform>/<cpu-arch>` dir can be included into this PR.

[extra commit]: https://github.com/libffi/libffi/commit/1a4b78

### CODE REVIEW

**Comment by indutny** [comment]
cc @addaleax

**Comment by indutny** [comment]
It builds and passes tests on 64bit linux, but I'm at loss about what's wrong with windows.

**Comment by indutny** [comment]
@addaleax I believe the only remaining step would be re-generating the configuration files for every platform. FWIW, the idea is to:

```sh
git clone git://github.com/indutny/node-ffi-napi -b feature/macos-arm64
cd node-ffi-napi/deps/libffi
./configure --enable-static --disable-shared --disable-builddir --with-pic
cp -rf {fficonfig.h,include/ffi.h,include/ffitarget.h} config/<platform>/<cpu-arch> 
```

where <platform> is one of: `freebsd`, `linux`, `mac`, `openbsd,` `solaris`, `win`, and `<cpu-arch>` is one of `arm`, `arm64`, `ia32`, `x64`.

I'm going to run it for 64bit linux, and freebsd, but other platforms are sadly out of my reach. Anyone wants to help?

**Comment by KishanBagaria** [comment]
Confirming this fixes #118 for me

**Comment by addaleax** [comment]
https://github.com/node-ffi-napi/node-ffi-napi/commit/d1ac0c310b62ad9611d566e38abf7f0e4fa2c0e4, generated using the steps you provided :)

**Comment by indutny** [comment]
Yay! Thanks @addaleax

**Comment by indutny** [comment]
@addaleax I think this is ready to be landed. There are no other platforms I could get config files for, and I made the best effort to cover 32bit freebsd and macos (although, I don't know for sure if they work). As discussed, this can be released as a major version bump, and we can add support for other platforms upon bug reports.

**Comment by dennisameling** [comment]
Was trying to add Windows ARM64 to the mix (which is supported by [libffi](https://github.com/libffi/libffi#supported-platforms)), but the regular `configure` command doesn't seem to work for that platform. 

Their README [does mention](https://github.com/libffi/libffi#installing-libffi) something about ARM64 though:

> To build static library for ARM64 with MSVC using visual studio solution, msvc_build folder have aarch64/Ffi_staticLib.sln required header files in aarch64/aarch64_include/

I can indeed build the static library using MSVC, but that doesn't help for this PR if I understand correctly. Will try to figure out how to get that working in the coming days, if anyone has any suggestions, they're very much welcome 🕵🏼

**Comment by indutny** [comment]
@dennisameling good point! Although, the `./configure` can't be run - the libffi team actually included the `ffi.h` and `fficonfig.h` files in the `msvc_build` folder. I've added them to this PR. Could you give it a try?

**Comment by indutny** [comment]
ah, nvm. I'll have to figure out the assembly as well.

**Comment by dennisameling** [comment]
Thanks @indutny! I was getting `'ml64' is not recognized as an internal or external command, operable program or batch file.` 

That's because of this logic:

https://github.com/node-ffi-napi/node-ffi-napi/blob/c1143a90596ab0a8a47ec490c29993d8397f91db/deps/libffi/libffi.gyp#L58-L62

Looking at `msvcc.sh`, it should be possible to set `armasm64` for ARM64, which I just tried, then ran into `BUILD_ASM : error A2029: unknown command-line argument or argument value /c [C:\repos\node-ffi-napi\build\deps\libffi\ffi.vcxproj]`.

After fixing that, it works 🎉

Here's my commit that fixes the build for ARM64:

https://github.com/dennisameling/node-ffi-napi/commit/f42cc2496f29b772f2ef5ecce5a2c72b3e18f9cd

Output of `npm test`:

```
84 passing (3s)
  1 pending
```

**Comment by indutny** [comment]
@dennisameling this is so awesome. Thanks for doing it! I've pushed your commit to this branch. Let's see if appveryor is as happy about it as github is 😂

**Comment by indutny** [comment]
@dennisameling completely offtopic, but I couldn't leave out the fact that apparently we are both trying to make Signal Desktop app work on ARM64 OSes!

**Comment by dennisameling** [comment]
@indutny yes! 😊 super glad we can combine our efforts this way! Hope there will be hosted CI for both Windows + MacOS arm64 soon, it makes things easier and more reliable for maintainers 🚀

**Comment by addaleax** [comment]
Okay, I already asked @indutny about this, but should we release this as semver-major? If I understand correctly, this PR would currently drop support for some platforms, so it seems like that’s a reasonable idea even if there aren’t that many users of those platforms to begin with?

**Comment by jkruse-ibm** [comment]
I executed the steps mentioned in on an s390x (Linux on Z) machine - all steps worked except for `npm test` which fails with the following output. Do you know what I need to do here to get it to work?

```
[*** node-ffi-napi]$ npm test

> ffi-napi@3.1.0 test /tmp/ffi-napi-archtest/node-ffi-napi
> node-gyp rebuild --directory test && nyc mocha --expose-gc --reporter spec

make: Entering directory '/tmp/ffi-napi-archtest/node-ffi-napi/test/build'
  CC(target) Release/obj.target/nothing/../node_modules/node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node_modules/node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/ffi_tests/ffi_tests.o
  SOLINK_MODULE(target) Release/obj.target/ffi_tests.node
  COPY Release/ffi_tests.node
make: Leaving directory '/tmp/ffi-napi-archtest/node-ffi-napi/test/build'
/usr/bin/node: symbol lookup error: /tmp/ffi-napi-archtest/node-ffi-napi/build/Release/ffi_bindings.node: undefined symbol: ffi_prep_cif_machdep
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
npm ERR! Test failed.  See above for more details.
```

**Comment by indutny** [comment]
@jkruse-ibm thanks for looking into this! I've added relevant source files to the build system, could you give it another go, please? (you'll need to run the `./configure` and the rest of the steps again, I'm afraid).

**Comment by jkruse-ibm** [comment]
@indutny You'r welcome. I executed the steps from above again with a small adjustment for s390x config folders:

```
git clone git://github.com/indutny/node-ffi-napi -b feature/macos-arm64
cd node-ffi-napi/deps/libffi
./configure --enable-static --disable-shared --disable-builddir --with-pic
mkdir -p config/linux/s390x
cp -lf {fficonfig.h,include/ffi.h,include/ffitarget.h} config/linux/s390x
rm {fficonfig.h,include/ffi.h,include/ffitarget.h}
cd ../..
npm install
```

But during `npm install` it fails (if you need full log I can provide it to you) with the following error:

```
../deps/libffi/src/java_raw_api.c:337:1: note: declared here
 ffi_prep_java_raw_closure_loc (ffi_java_raw_closure* cl,
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
../deps/libffi/src/closures.c: In function ‘allocate_space’:
../deps/libffi/src/closures.c:748:29: warning: comparison of integer expressions of different signedness: ‘off_t’ {aka ‘long int’} and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
       off_t to_write = (len < page_size) ? len : page_size;
                             ^
../deps/libffi/src/closures.c:748:44: warning: operand of ?: changes signedness from ‘off_t’ {aka ‘long int’} to ‘size_t’ {aka ‘long unsigned int’} due to unsignedness of other operand [-Wsign-compare]
       off_t to_write = (len < page_size) ? len : page_size;
                                            ^~~
make: *** No rule to make target 'Release/obj.target/ffi/deps/libffi/src/s390x/ffi.o', needed by 'Release/obj.target/deps/libffi/libffi.a'.  Stop.
make: Leaving directory '/tmp/node-ffi-napi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.18.0-240.10.1.el8_3.s390x
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/node-ffi-napi
gyp ERR! node -v v10.21.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi-napi@3.1.0 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffi-napi@3.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jakob/.npm/_logs/2021-02-16T07_44_10_855Z-debug.log
```

**Comment by indutny** [comment]
@jkruse-ibm my bad, I've made a typo in the build config file. Could you try it one more time, please?

**Comment by indutny** [comment]
@addaleax I know that s390x is still pending, but I don't think that should block the release if you'd like to do one. Seems like we can always do a patch release with proper support for it once it is there. Is there anything I could do to help you with review?

**Comment by addaleax** [comment]
Nope, I'll just merge and release this. Thank you for all the hard work!

**Comment by indutny** [comment]
Thank you @addaleax , and everyone here!

**Comment by addaleax** [comment]
`📦  ffi-napi@4.0.1` :rocket:

**Pull request merged**
