### PR TITLE
Fix crasher in callback calls

### PR DESCRIPTION
**Pull request by atishay**
Fixes https://github.com/node-ffi-napi/node-ffi-napi/issues/52
See https://github.com/node-ffi/node-ffi/blob/master/lib/callback.js#L78

### CODE REVIEW

**Comment by mygig** [comment]
@addaleax  is it possible to get this PR in sooner ?

**Comment by addaleax** [comment]
@mygig This is on my TODO list, but it takes some time to dig into and I’m maintaining this project in my sparetime. 

I explicitly removed these lines in 2a1e6f0d95416dd650a9ba7bedd4235dfda2ab23 because, if I remember correctly, they were adding a memory leak by keeping C function references alive indefinitely when managing the lifetime should be the responsibility of the library that uses node-ffi-napi.

I’ll still take a deeper look, though.

**Comment by Artemkaaas** [comment]
Hello, @addaleax 
Any updates on this issue? 
We have the same segfault crash after [migration](https://github.com/hyperledger/indy-sdk/pull/2021/files) from `ffi` to `ffi-napi`.

**Comment by doggkruse** [comment]
This PR fixes the crash I'm seeing when migrating from node-ffi

**Comment by bruceauyeung** [comment]
lately i also encountered this problem, this take me  about 3 days to dig it out because my electron app crashed without any error/info. 
thanks @atishay, you saved my life!

**Comment by addaleax** [comment]
Okay, given that I won’t have time to dig deeper for a while, I’ll merge this.

However, **please be aware that this *does* introduce a memory leak**. This trades off a usability issue – the fact that you have to keep your native callbacks alive manually – for a real bug. This is **not** a good permanent solution.

**Comment by bruceauyeung** [comment]
@addaleax if not applying this patch, how should i do to avoid callback func being GCed?  can you give a sample code snippet ?

**Comment by Venryx** [comment]
>lately i also encountered this problem, this take me about 3 days to dig it out because my electron app crashed without any error/info.
> thanks @atishay, you saved my life!

Oh my gosh, same thing here. 💢

In my case it was 4 hours instead of 3 days, but it was driving me insane nonetheless.

Like some others here, I've been migrating a project of mine from the unmaintained `ffi` package to `ffi-napi`. I thought I must be doing something wrong -- some mistake in my native-function definitions or something that used to be safe-handled in `ffi`, but not in `ffi-napi`.

I was such a fool to not have just looked through the library's issues list for others hitting crashing bugs from `ffi` -> `ffi-napi` migration. I guess it's because I didn't have an actual "error message" to search for, but nonetheless a regular manual scanning should still have been done.

To prevent stupidity like this in the future, I'm now putting together a "what to do if you hit a tricky bug" procedure:
```
Procedure for when hitting a tricky bug
==========
1) Do regular narrowing-down for a bit. (If taking more than a few minutes, and you're pretty sure you've identified which library the issue could be in: pause, and move to step 2!)
2) Search for error in library's issues list.
3) Search for error on google. (if error distinct enough)
4) Make sure you've tried the latest version. (if not already on it, and easy to upgrade)
5) Scan through library's issues list manually.
```

**Pull request merged**
