### PR TITLE
Update to node-addon-api v3.0.0

### PR DESCRIPTION
**Pull request by joelpurra**

### CODE REVIEW

**Comment by joelpurra** [comment]
Update is, from my point of view, unrelated to the previously reported `node-addon-api` vulnerability. Fixes #85 though.

**Comment by addaleax** [comment]
It fixes the warning, but this is a semver-major change as I understand it. I’d be reluctant to issue a new semver-major release just to fix a warning, unless this is particularly important (the same goes for https://github.com/node-ffi-napi/ref-napi/pull/44)

**Comment by joelpurra** [comment]
@addaleax: upgrading `node-addon-api` fixes errors I see in a project which is using both `ffi-napi` and `ref-napi`. Sorry for not giving additional details before.

Last time I was working on this project was I was using nodejs v12 (before nodejs v14 was released), and everything worked as expected. The project still works with nodejs v12, but not with v14. See output below.

I'll created pull requests for Node.js v14 and see if the CI tests can catch this.

- https://github.com/node-ffi-napi/node-ffi-napi/pull/94
- https://github.com/node-ffi-napi/ref-napi/pull/45

Yeah, I also think it'd be a semver-major change for both `ffi-napi` and `ref-napi`. Would also target the upgraded `ref-napi` from `ffi-napi` while at it, to keep the `node-addon-api` versions on par.

```text
#
# Fatal error in , line 0
# Check failed: result.second.
#
#
#
#FailureMessage Object: 0x7ffd84fab460
 1: 0xa6f5f1  [node]
 2: 0x19cb8c4 V8_Fatal(char const*, ...) [node]
 3: 0xe58379 v8::internal::GlobalBackingStoreRegistry::Register(std::shared_ptr<v8::internal::BackingStore>) [node]
 4: 0xba38a8 v8::ArrayBuffer::GetBackingStore() [node]
 5: 0x9c1290 napi_get_typedarray_info [node]
 6: 0x7f162045946a  [/some/project/node_modules/ffi-napi/node_modules/ref-napi/prebuilds/linux-x64/node.napi.node]
 7: 0x7f1620459d2d  [/some/project/node_modules/ffi-napi/node_modules/ref-napi/prebuilds/linux-x64/node.napi.node]
 8: 0x7f1620443de7 FFI::WrapPointerImpl(Napi::Env, char*, unsigned long) [/some/project/node_modules/ffi-napi/build/Release/ffi_bindings.node]
 9: 0x7f1620445b05 FFI::FFI::InitializeBindings(Napi::Env, Napi::Object) [/some/project/node_modules/ffi-napi/build/Release/ffi_bindings.node]
10: 0x7f162044681b FFI::InitializeBindings(Napi::CallbackInfo const&) [/some/project/node_modules/ffi-napi/build/Release/ffi_bindings.node]
11: 0x7f162044765b Napi::details::CallbackData<Napi::Value (*)(Napi::CallbackInfo const&), Napi::Value>::Wrapper(napi_env__*, napi_callback_info__*) [/some/project/node_modules/ffi-napi/build/Release/ffi_bindings.node]
12: 0x9b8a5f  [node]
13: 0xbe254b  [node]
14: 0xbe3af6  [node]
15: 0xbe4176 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
16: 0x13fe0b9  [node]
Illegal instruction (core dumped)
```

**Comment by joelpurra** [comment]
Seems some tests are failing on Node.js v14 for `ref-napi`, although it's not clear if it's the same error as I get (see previous error output). I'll push the `node-addon-api` v3.0.0 update to that branch to check if it'll fix it.

**Comment by addaleax** [comment]
>  If I upgrade `node-addon-api` to v3.0.0 the project works again.

Are you sure it’s because of the update of `node-addon-api`? There were known incompatibilities with Node v14.x, but they should all have been resolved now, although that was in a semver-major update of ref-napi (v2.x) and node-ffi-napi (v3.x). Those incompatibilities would have led to the exact error message you’re posting above, so maybe you were using an older version of these modules?

If upgrading node-addon-api does fix something on v14.x, I’d be surprised, because that probably requires some more investigation as to why the bug is occurring in the first place.

**Comment by joelpurra** [comment]
> Are you sure it’s because of the update of `node-addon-api`?

@addaleax: nope it was not because of `node-addon-api` -- it only seemed like a fix because of a side-effect during testing the fix. See #96 

This pull request (and https://github.com/node-ffi-napi/ref-napi/pull/44) can be left open, merged, or be closed, that's up to you. Note that (at least) [`weak-napi`](https://github.com/node-ffi-napi/weak-napi/) is using `node-addon-api` v3.0.0, and it might be good to keep these dependenies on par?

**Comment by addaleax** [comment]
`📦  ffi-napi@4.0.1` :rocket:

**Pull request merged**
