### PR TITLE
node-ffi-napi : adding support for aarch64 architecture

### PR DESCRIPTION
**Pull request by ossdev07**
added support in libffi corresponding to  aarch64 (ARM64) architecture
Signed-off-by: ossdev07 <ossdev@puresoftware.com>

### CODE REVIEW

**Comment by rhenwood-arm** [comment]
Hi @addaleax and @Kaiepi  : can you review this PR and consider landing?

**Comment by addaleax** [comment]
Sorry, thanks for the ping. @ossdev07 @rhenwood-arm Does this correspond to upstream changes in libffi in some way? Could you link to that so that I’m aware of what exactly this changes in comparison to upstream?

**Comment by ossdev07** [comment]
> Sorry, thanks for the ping. @ossdev07 @rhenwood-arm Does this correspond to upstream changes in libffi in some way? Could you link to that so that I’m aware of what exactly this changes in comparison to upstream?

@addaleax we picked ARM specific changes from PR
https://github.com/libffi/libffi/pull/490

**Comment by Kaiepi** [comment]
I've never done anything related to ARM64 before, so I don't really have much to say. If libffi supports ARM64 on FreeBSD and OpenBSD, I think config headers for those should be included with this, if possible.

**Comment by ossdev07** [comment]
@Kaiepi I will provide another patch by including the config headers for FreeBSD and OpenBSD. 

Thanks for the feedback!

**Comment by rhenwood-arm** [comment]
@Kaiepi : It would be great for me if this could be landed.

**Comment by Kaiepi** [comment]
I'll review this. It'll probably take me a week or two to finish since I don't have time on weekdays for this and I don't know Linux or aarch64 all that well, so there'll be some reading I need to do beforehand.

**Comment by ossdev07** [comment]
@Kaiepi Did you get the time to review this patch, It will be great if this could be landed. @addaleax

**Comment by Kaiepi** [comment]
Agh, sorry this took so long @ossdev07, I didn't realize most of this is just code from libffi earlier. This looks alright to me.

**Pull request merged**
